- name: Demo on printing
  hosts: localhost
  tasks:
    - name: Print Hello world
      ansible.builtin.debug:
        msg: Hello world

- name: Demo on vars
  hosts: localhost
  vars:
    URL: example.com
  tasks:
    - name: print a variable
      ansible.builtin.debug:
        msg: "{{ URL }}"

- name: Demo on task level vars
  hosts: localhost
  vars:
    URL: play.example.com
  tasks:

    - name: print a variable
      ansible.builtin.debug:
        msg: "{{ URL }}"
      vars:
        URL: task.example.com
    - name: print play variable
      ansible.builtin.debug:
        msg: "{{ URL1 }}"