- name: Demo on printing
  hosts: localhost
  tasks:
    - name: Print Hello world
      ansible.builtin.debug:
        msg: Hello world

- name: Demo on vars
  hosts: localhost
  Vars:
    URL:  number.com
  tasks:
    - name: print a variable
      ansible.builtin.debug:
        msg: "{{ URL }}"