- name: Print Used Memory
  hosts: localhost
  tasks:
    - name: Get Memory
      ansible.builtin.shell: free | grep Mem | xargs
      register: free

    - name: set fact
      ansible.builtin.set_fact:
      FREE: "{{ free.stdout | split(' ') }}"